# Use root/example as user/password credentials
version: '3.7'

services:
  database:
    image: mariadb
    restart: always
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: Volvo240
      MYSQL_USER: user
      MYSQL_PASSWORD: Volvo240
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - back
  app:
    build: ../
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - back

networks:
  back:
    driver: bridge